### ISSUE TITLE
Bangladesh Visa

### ISSUE THREAD

**Issue by lauradereynal** [mozillafordevelopment/fieldresearch#29]

**Comment by sjturner01** [comment]
You can get a Bangladesh Visa upon arrival at the airport. Here are handy instructions from Andrew..

 Once you arrive you will head towards immigration. When you turn the corner you will see two signs for “On Arrival VISAs” one pointing towards a small room behind glass with a clerk and one pointing towards the police desk. Go to the police desk and hand them your paperwork. For me, they only wanted to see my Passport, my arrival card, and the phone number of the hotel. The police officer will hand you back your papers and tell you to pay for your VISA and then come back. The VISA costs $51 USD which I just payed for in cash. If you have exact change it helps as they don’t have much to break bills with. Once the clerk takes your fee, they will fill out a receipt which you then take back over to the police desk where they will finalize your VISA application. Once that is done, go stand in line at immigration where it says “Same Day VISA”. The immigration officer will ask to see your hotel reservation and ask you some basic questions.

**Comment by lauradereynal** [comment]
Thanks !!
