### ISSUE TITLE
Design research contributors

### ISSUE THREAD

**Issue by k88hudson** [mozillafordevelopment/fieldresearch#71]
I'd love to add a section to the contributor guide (http://webmaker-mobile-guide.mofodev.net) for design contributors. Are there specific asks we could give to people interested in helping out?

Happy to discuss in a meeting if that makes more sense

**Comment by k88hudson** [comment]
@LauraReynal @thisandagain

**Comment by thisandagain** [comment]
++++! 
cc @flukeout

**Comment by thisandagain** [comment]
A meeting might be easiest to kick this off once @LauraReynal returns from Bangladesh.

**Comment by lauradereynal** [comment]
Hey, do you want to talk about this now that Bangladesh and MozFest are over ? What is your idea @k88hudson ?
